### PR TITLE
Update devise

### PR DESCRIPTION
**Pull request by PeterWuMC**
@dawid-sklodowski @sparrovv @amar-shah

Update devise_ldap_authenticatable to the upstream master so we can update and use the latest devise.

### CODE REVIEW

**Comment by amar-shah** [comment]
Does this not need testing by QA for Chopin, CoCo, Claims App etc etc?

**Comment by PeterWuMC** [comment]
@amar-shah the testing bit would be tagged in the respective app.

actually you might know, why do we need this fork? what is this fail over?

**Comment by dawid-sklodowski** [comment]
Its tough to review PR merging upstream master.

However..
Anyways in Chopin config you have:

```yml
base_config: &BASE_CONFIG
 servers:
   - host: 10.1.3.10  # salmon.sks.xbridge.com
     port: 3269
   - host: 10.1.3.12  # tuna.sks.xbridge.com
     port: 3269
```
So there are 2 LDAP servers. Devise ldap extension has to support connecting to other server if first one fails

Otherwise you can also delete other LDAP server with this PR, as there will be no point in maintaining redundancy.

Wrapping up -- I'm happy with this PR if failover works.

**Comment by dawid-sklodowski** [comment]
BTW we never pull-requested our fork towards upstream.
If they merged it would solve maintenance issues.

**Comment by amar-shah** [comment]
@PeterWuMC you wrote :- 

>@amar-shah the testing bit would be tagged in the respective app.

> actually you might know, why do we need this fork? what is this fail over?

Can we issue these PR's and get sign off, I would like to go make sure all apps are using this version of the gem, as part of this PR.

**Comment by amar-shah** [comment]
Signed-off-by:- @amar-shah

**Pull request merged**
